### PR TITLE
Add Gradient-boosted equivalent sources paper

### PR DESCRIPTION
**Pull request by santisoler**
Add new entry in publications with the latest paper: Gradient-boosted equivalent sources.

### CODE REVIEW

**Comment by leouieda** [comment]
👀  https://www.compgeolab.org/publications/eql-gradient-boosted.html

**Comment by santisoler** [comment]
Yes! Found it myself right after I opened the other PR.

**Comment by santisoler** [comment]
And I also forgot that we now we have a `main` branch 🤦🏼‍♂️ 

Should be ready now!

**Comment by leouieda** [comment]
😆

**Pull request merged**
