### PR TITLE
News item about Science Day 2024

### PR DESCRIPTION
**Pull request by YagoMCastro**
Post about Arthur's and my presentaions at IAG | Science Day 2024

### CODE REVIEW

**Comment by santisoler** [comment]
Awesome @YagoMCastro! Thanks for opening this PR. I'm merging this.

I would like to add a macro for adding links to the YouTube videos. I'll open a different PR for that one shortly.

**Comment by leouieda** [comment]
Good work!

**Comment by leouieda** [comment]
@YagoMCastro if you want (or as a reference for future posts) you could separate the post in a section per talk and also include the abstracts if you have them. That adds keywords for search and also provides more context for anyone interested.

**Comment by YagoMCastro** [comment]
Good idea!! I'll talk to Arthur and elaborate on a more complete post.

**Pull request merged**
