### PR TITLE
Add a lab manual to establish guides and culture

### PR DESCRIPTION
**Pull request by leouieda**
This manual is based on the excellent Lab Carpentry blueprints (http://labcarpentry.org), 
with material adapted from the Data Intensive Biology Lab (http://ivory.idyll.org/lab) and 
the Data Exploration Lab (https://data-exp-lab.github.io).

### CODE REVIEW

**Comment by leouieda** [comment]
@santisoler sorry for rush in merging this in. I kind of wanted to have it out before my meeting with the students tomorrow. Please have a look and see if you'd like to change anything.

**Comment by santisoler** [comment]
No problem @leouieda ! I think the texts look very nice. I would just add a Next Page and Previous Page buttons after the text of each section. That would improve navigability (now I need to find the next page on the TOC). I don't remember if Urubu has a quick way to do this...
Besides, is there an option to highlight the current page on the TOC?

**Comment by leouieda** [comment]
> I would just add a Next Page and Previous Page buttons after the text of each section.

That's a good idea. I think there is an easy way in Urubu.

**Comment by leouieda** [comment]
> Besides, is there an option to highlight the current page on the TOC?

Probably. The template `_layouts/manual.html` draws the TOC and there could be a check if the page is the current page, apply a different class to it.

**Pull request merged**
