### PR TITLE
News item about the new members joining in 2021

### PR DESCRIPTION
**Pull request by leouieda**
Briefly introduces India, Gelson, Sarah, Laura, and Hamed.

### CODE REVIEW

**Comment by leouieda** [comment]
@indiauppal @SAskevold @LNich @HamedAlsalehi could you please confirm if you're OK with me mentioning your names in this news item (click on the "Files changed" tab to read it)? It's perfectly fine if you'd rather not be mentioned or prefer first/last name only, I completely understand.

**Comment by indiauppal** [comment]
I'm ok with you mentioning my name.

**Comment by LNich** [comment]
I'm fine with you mentioning my full name.

**Comment by SAskevold** [comment]
I'm okay with this as well.

**Comment by HamedAlsalehi** [comment]
im okay with this

**Comment by leouieda** [comment]
Gelson gave his approval as well

**Pull request merged**
